name: Hw wf

on:
  push: 
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        # run: sudo service mysql start
        run: mysql -u root -p database.sql
        shell: bash
