name: Hw wf

on:
  push: 
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: /var/run/mysqld/mysql.server
        shell: bash
