name: Hw wf

on:
  push: 
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: sudo service mysql start

      - name: create table
        run: mysql -u root -p actionsJava database.sql
        shell: bash
