name: Setup

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL and Java program
        run: |
          sudo service mysql start
          sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS actionsJava;"
          sudo mysql -u root -proot actionsJava < database.sql
          javac Main.java
          java -cp .:mysql-connector-java-8.2.0.jar Main < input.txt
          1
          2
          raku4
        shell: bash
