name: Setup mysql and create database

on:
  push: 
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start mysql
        run: sudo service mysql start

      - name: create database
        run: |
          sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS actionsJava;"
          sudo mysql -u root -proot actionsJava < database.sql
        # run: |
        #   mysql -u root -p
        #   GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'password';
        shell: bash
